name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_chromium_and_build:
    runs-on: ubuntu-latest

    container:
      image: erolatex/selenoid_base_image:1.0.1

    steps:
      - name: Set up the environment
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository -y ppa:xtradeb/apps
          apt-get update

      - name: Check Chromium Version
        run: |
          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > current_chromium_version.txt
          awk -F '.' '{print $1 "." $2}' current_chromium_version.txt > short_chromium_version.txt
        id: check_version

      - name: Compare versions
        run: |
          if [ -f last_chromium_version.txt ]; then
            diff last_chromium_version.txt current_chromium_version.txt || true;
          else
            echo "No previous version found."
          fi
        id: version_check

      - name: Clone Dockerfile Repository
        if: steps.version_check.outcome == 'failure'
        uses: actions/checkout@v3
        with:
          repository: erolatex/images
          path: images

      - name: Set up Docker Buildx
        if: steps.version_check.outcome == 'failure'
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: steps.version_check.outcome == 'failure'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: steps.version_check.outcome == 'failure'
        run: |
          cd images/static/chromium
          docker buildx build --no-cache --build-arg BASE_IMAGE_TAG=1.0.1 \
            --platform linux/amd64,linux/arm64 \
            -t erolatex/selenoid_chromium:$(cat ../../../short_chromium_version.txt) \
            -t erolatex/selenoid_chromium:latest \
            --push .

      - name: Save current Chromium version
        if: steps.version_check.outcome == 'failure'
        run: |
          echo "Saving the current Chromium version."
          cp current_chromium_version.txt last_chromium_version.txt

      - name: Cache last version
        if: steps.version_check.outcome == 'failure'
        # Make sure the last_chromium_version.txt file is cached
        uses: actions/cache@v3
        with:
          path: last_chromium_version.txt
          key: chromium-version-cache
          restore-keys: |
            chromium-version-cache
