name: Build and Push Docker Image

# Trigger the workflow to run on a schedule (daily at midnight UTC) or manually
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_chromium_and_build:
    runs-on: ubuntu-latest

    container:
      image: erolatex/selenoid_base_image:1.0.1

    steps:
      - name: Set up the environment
        # Install necessary tools and add the PPA for Chromium (without sudo)
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository -y ppa:xtradeb/apps
          apt-get update

      - name: Check Chromium Version
        # Fetch the Chromium version and extract the major version (e.g., 129.0)
        run: |
          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > current_chromium_version.txt
          awk -F '.' '{print $1 "." $2}' current_chromium_version.txt > short_chromium_version.txt
        id: check_version

      - name: Cache last version
        # Cache the last Chromium version to compare with the current one
        uses: actions/cache@v3
        with:
          path: last_chromium_version.txt
          key: chromium-version-cache
          restore-keys: |
            chromium-version-cache

      - name: Compare versions
        # Compare the current and last Chromium versions
        run: |
          if [ -f last_chromium_version.txt ]; then
            diff last_chromium_version.txt current_chromium_version.txt || true;
          fi
        id: version_check

      - name: Clone Dockerfile Repository
        # Clone the Dockerfile repository if there is a Chromium update
        if: steps.version_check.outcome == 'failure'
        uses: actions/checkout@v3
        with:
          repository: erolatex/images
          path: images

      - name: Set up Docker Buildx
        # Set up Docker Buildx for multi-platform builds
        if: steps.version_check.outcome == 'failure'
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        # Authenticate to Docker Hub to push the built image
        if: steps.version_check.outcome == 'failure'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        # Build and push the Docker image with the updated Chromium version
        if: steps.version_check.outcome == 'failure'
        run: |
          cd images/static/chromium
          docker buildx build --no-cache --build-arg BASE_IMAGE_TAG=1.0.1 \
            --platform linux/amd64,linux/arm64 \
            -t erolatex/selenoid_chromium:$(cat ../../../short_chromium_version.txt) \
            -t erolatex/selenoid_chromium:latest \
            --push .

      - name: Save current Chromium version
        # Save the current version for the next workflow run
        if: steps.version_check.outcome == 'failure'
        run: |
          cp current_chromium_version.txt last_chromium_version.txt
