name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_chromium_version:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up the environment
        run: |
          sudo apt-get update && sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:xtradeb/apps
          sudo apt-get update

      - name: Restore last Chromium version from cache
        id: cache_last_version
        uses: actions/cache@v3
        with:
          path: last_chromium_version.txt
          key: chromium-version-cache
          restore-keys: |
            chromium-version-cache

      - name: Check Chromium Version
        id: get_full_version
        run: |
          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > current_chromium_version.txt
          echo "full_version=$(cat current_chromium_version.txt)" >> $GITHUB_ENV

      - name: Extract Short Version
        id: get_short_version
        run: |
          awk -F '.' '{print $1 "." $2}' current_chromium_version.txt > short_chromium_version.txt
          echo "short_version=$(cat short_chromium_version.txt)" >> $GITHUB_ENV

      - name: Compare with the last version
        id: compare_versions
        run: |
          if [ -f last_chromium_version.txt ]; then
            if diff last_chromium_version.txt current_chromium_version.txt > /dev/null; then
              echo "Chromium version has not changed. Skipping build."
              echo "build_required=false" >> $GITHUB_ENV
            else
              echo "Chromium version has been updated."
              echo "build_required=true" >> $GITHUB_ENV
            fi
          else
            echo "No previous version found. Proceeding with build."
            echo "build_required=true" >> $GITHUB_ENV

      - name: Cache the current Chromium version
        if: always()
        uses: actions/cache@v3
        with:
          path: current_chromium_version.txt
          key: chromium-version-cache
          restore-keys: |
            chromium-version-cache

  build_and_push:
    needs: check_chromium_version
    if: env.build_required == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB.DOCKER_PASSWORD }}

      - name: Clone Dockerfile Repository
        uses: actions/checkout@v3
        with:
          repository: erolatex/images
          path: images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          cd images/static/chromium
          docker buildx build --no-cache --build-arg BASE_IMAGE_TAG=1.0.1 \
            --platform linux/amd64,linux/arm64 \
            -t erolatex/selenoid_chromium:${{ env.short_version }} \
            -t erolatex/selenoid_chromium:latest \
            --push .
