name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_chromium_version:
    runs-on: ubuntu-22.04
    outputs:
      build_required: ${{ steps.compare_versions.outputs.build_required }}
      short_version: ${{ steps.get_short_version.outputs.short_version }}

    steps:
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:xtradeb/apps
          sudo apt-get update

      - name: Create cache directory
        run: mkdir -p ./cache

      - name: Restore last Chromium version from cache
        id: cache_last_version
        uses: actions/cache@v3
        with:
          path: ./cache/current_chromium_version.txt
          key: chromium-version-cache-${{ github.run_id }}

      - name: Check Chromium Version
        id: get_full_version
        run: |
          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > ./cache/current_chromium_version.txt
          echo "full_version=$(cat ./cache/current_chromium_version.txt)" >> $GITHUB_ENV

      - name: Extract Short Version
        id: get_short_version
        run: |
          awk -F '.' '{print $1 "." $2}' ./cache/current_chromium_version.txt > ./cache/short_chromium_version.txt
          echo "short_version=$(cat ./cache/short_chromium_version.txt)" >> $GITHUB_ENV

      - name: Compare with the last version
        id: compare_versions
        run: |
          if [ ! -f ./cache/last_chromium_version.txt ]; then
            echo "No previous version found. Proceeding with build."
            echo "build_required=true" >> $GITHUB_ENV
          else
            if diff ./cache/last_chromium_version.txt ./cache/current_chromium_version.txt > /dev/null; then
              echo "Chromium version has not changed. Skipping build."
              echo "build_required=false" >> $GITHUB_ENV
            else
              echo "Chromium version has been updated."
              echo "build_required=true" >> $GITHUB_ENV
            fi
          fi

      - name: Cache the current Chromium version
        uses: actions/cache@v3
        with:
          path: ./cache/current_chromium_version.txt
          key: chromium-version-cache-${{ github.run_id }}
