name: Build and Push Chromium Image

on:
  workflow_dispatch:

jobs:
  check_chromium_version:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Chromium Version
        run: |
          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > ./cache/current_chromium_version.txt
          SHORT_VERSION=$(awk -F '.' '{print $1 "." $2}' ./cache/current_chromium_version.txt)
          echo "short_version=${SHORT_VERSION}" >> $GITHUB_ENV

      - name: Check Image on Docker Hub
        run: |
          curl --silent -f -lSL https://hub.docker.com/v2/repositories/erolatex/selenoid_chromium/tags/${{ env.short_version }}/ || echo "Not Found" > check_result.txt
        id: check_docker

  build_and_push:
    needs: check_chromium_version
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB.DOCKER_PASSWORD }}

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t erolatex/selenoid_chromium:${{ env.short_version }} \
            -t erolatex/selenoid_chromium:latest \
            --push .
