name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_chromium_version:
    runs-on: ubuntu-22.04
    outputs:
      short_version: ${{ steps.get_short_version.outputs.short_version }}
      full_version: ${{ steps.get_full_version.outputs.full_version }}

    steps:
      - name: Set up the environment
        run: |
          sudo apt-get update && sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:xtradeb/apps
          sudo apt-get update

      - name: Check Chromium Version
        id: get_full_version
        run: |
          apt-cache madison chromium | grep xtradeb/apps | awk '{print $3}' > current_chromium_version.txt
        outputs:
          full_version: ${{ steps.get_full_version.outputs.full_version }}

      - name: Extract Short Version
        id: get_short_version
        run: |
          awk -F '.' '{print $1 "." $2}' current_chromium_version.txt > short_chromium_version.txt
        outputs:
          short_version: ${{ steps.get_short_version.outputs.short_version }}

      - name: Save versions for future steps
        run: |
          echo "Full version: $(cat current_chromium_version.txt)"
          echo "Short version: $(cat short_chromium_version.txt)"

  build_and_push:
    needs: check_chromium_version
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB.DOCKER_PASSWORD }}

      - name: Clone Dockerfile Repository
        uses: actions/checkout@v3
        with:
          repository: erolatex/images
          path: images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          cd images/static/chromium
          docker buildx build --no-cache --build-arg BASE_IMAGE_TAG=1.0.1 \
            --platform linux/amd64,linux/arm64 \
            -t erolatex/selenoid_chromium:${{ needs.check_chromium_version.outputs.short_version }} \
            -t erolatex/selenoid_chromium:latest \
            --push .
